version: 2.1

workflows:
  version: 2
  build_all:
    jobs:
      - build

  test-daily:
    triggers:
    - schedule:
        cron: "0 6 * * *"
        filters:
          branches:
            only: main
    jobs:
    - build

jobs:
  build:
    shell: /bin/bash --login -eo pipefail

    macos:
      xcode: '13.4.1'

    steps:
    - checkout

    - run:
        name: Make Output Directory
        command: mkdir -p 'artifacts'

    - run:
        name: Build hello-ios
        command: xcodebuild build -workspace 'hello-ios.xcworkspace' -scheme 'hello-ios' CODE_SIGNING_ALLOWED=NO | tee 'artifacts/hello_ios_build_output.log' | xcpretty
        when: always

    - run:
        name: Build hello-watchOS
        command: xcodebuild build -workspace 'hello-ios.xcworkspace' -scheme 'hello-watchOS' CODE_SIGNING_ALLOWED=NO | tee 'artifacts/hello_watchos_build_output.log' | xcpretty
        when: always

    - run:
        name: Build hello-watchOS (Notification)
        command: xcodebuild build -workspace 'hello-ios.xcworkspace' -scheme 'hello-watchOS (Notification)' CODE_SIGNING_ALLOWED=NO | tee 'artifacts/hello_watchos_notification_build_output.log' | xcpretty
        when: always

    - store_artifacts:
        path: artifacts
